apiVersion: v1
kind: Service
metadata:
  labels:
    app: ref-kafka-app-producer-service-nodeport
  name: ref-kafka-app-producer-service-nodeport
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30111
  selector:
    app: ref-kafka-app-producer-deployment
  type: NodePort
status:
  loadBalancer: {}
